### ISSUE TITLE
XX-Hello can't open process for writing

### ISSUE THREAD

**Issue by vigilancetech-com** [zevlg/xwem#1]
Hi, I'm having a problem similar to this:

https://xwem-devel.nongnu.narkive.com/HKRdHoqS/error-compiling-xlib-and-xwem

I've deleted all but the latest packages available for sxemacs.

Still nothing.

Also, when I start xwem it never seems to be able to recognize my keystrokes even tho xev says my hyper_r key is bound to my windows (super) key.

I edited the 'sx' script to include '-listen tcp' in order to get xwem to not immediately error out

here's my xdpyinfo:

[xdpyinfo.txt](https://github.com/zevlg/xwem/files/5072392/xdpyinfo.txt)

**Comment by zevlg** [comment]
I’m sorry, but xwem is unsupported. I’ll archive this repo now
